import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class FakeBackendService {
  private jwt: string = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJBZG1pbiIsImF1dGhvcml0aWVzIjpbIkFETUlOIiwiVEVBQ0hFUiIsIlNUVURFTlQiXX0.ydAgHhrv5I0TUvxPlsmaja2JGDYxQdjittNBSQECSxY';
  private admins: any[] = [
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
  ];
  private teachers: any[] = [
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
  ];
  private students: any[] = [
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
  ];

  private examPeriods : any[] = [
    {_id: 1,
    name: 'January exam period',
    startDate: '2020-01-23',
    endDate: '2020-02-03'},
  {_id: 2,
    name: 'February exam period',
    startDate: '2020-02-04',
    endDate: '2020-02-14'
  },
  {_id: 3,
    name: 'April exam period',
    startDate: '2020-04-04',
    endDate: '2020-04-10'
  }];

  constructor() { }

  login(credentials: LoginCredentials): Observable<any> {
    if (credentials.username === 'admin' && credentials.password === 'admin') return of(this.jwt);
    else return of(null);
  }

  getAdmins(): Observable<any> {
    return of(this.admins);
  }

  getTeachers(): Observable<any> {
    return of(this.teachers);
  }

  getStudents(): Observable<any> {
    return of(this.students);
  }

  getExamPeriods() : Observable<any> {
    return of(this.examPeriods);
  }
}

interface LoginCredentials {
  username: string,
  password: string,
}
