import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { ExamPeriod } from './model/exam-period/exam-period';

@Injectable({
  providedIn: 'root'
})
export class FakeBackendService {
  private jwt: string = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJBZG1pbiIsImF1dGhvcml0aWVzIjpbIkFETUlOIiwiVEVBQ0hFUiIsIlNUVURFTlQiXX0.ydAgHhrv5I0TUvxPlsmaja2JGDYxQdjittNBSQECSxY';
  private admins: any[] = [
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["admin"],
      fullName: () => `Boris Jankovic`,
    },
  ];
  private teachers: any[] = [
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["teacher"],
      fullName: () => `Boris Jankovic`,
    },
  ];
  private students: any[] = [
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
    {
      id: 1,
      username: "brvj",
      firstName: "Boris",
      lastName: "Jankovic",
      address: "Pezos",
      phoneNumber: "021-123-456",
      email: 'brvj@gmail.com',
      authorities: ["student"],
      fullName: () => `Boris Jankovic`,
    },
  ];
  private courses: any[] = [
    {
      id: 1,
      name: "Mathematics 1",
    },
    {
      id: 1,
      name: "Mathematics 2",
    },
    {
      id: 1,
      name: "Mathematics 3",
    },
    {
      id: 1,
      name: "Mathematics 4",
    },
    {
      id: 1,
      name: "Mathematics 5",
    }];

  constructor() { }

  login(credentials: LoginCredentials): Observable<any> {
    if (credentials.username === 'admin' && credentials.password === 'admin') return of(this.jwt);
    else return of(null);
  }

  getAdmins(): Observable<any> {
    return of(this.admins);
  }

  getTeachers(): Observable<any> {
    return of(this.teachers);
  }

  getStudents(): Observable<any> {
    return of(this.students);
  }

  getCourses(): Observable<any>{
    return of(this.courses);

  }
}

interface LoginCredentials {
  username: string,
  password: string,
}
